### ISSUE TITLE
file missing when building

### ISSUE THREAD

**Issue by phdecloitre** [foxitsoftware/cordova-plugin-foxitpdf#1]
I followed all instruction and performed a build which failed in CLI and failled also in Xcode.
Xcode told me : defines.h : file not found.
What do you suggest .
Many thanks

**Comment by niuemperor** [comment]
Looks like the first step in the operation except when the error

> In your Xcode project, find the FoxitSource folder and "UI Extension" folder(in blue), right click and delete it, confirm "Remove Reference" when prompted. Create the FoxitSource group (in yellow) (because Cordova plug-in can not create iOS group).


Please refer to the video to see how the first step is to operate
Https://youtu.be/3stdbwcm68k
