### ISSUE TITLE
Unable to find explicit activity class.  have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by gsotiris** [foxitsoftware/cordova-plugin-foxitpdf#11]
hello, 

After installing this plugin and the the library as it is in the installation description when I am trying to open a pdf file i get this error. 

Unable to find explicit activity class {myApplicationId/com.foxit.cordova.plugin.ReaderActivity}; have you declared this activity in your AndroidManifest.xml?

On iOS it works perfect. 

I didn't find any solution to that, any suggestion?

**Comment by xinqiangSong** [comment]
Hi, are you sure the plugin is installed successfully,  can you find the **ReaderActivity** class in your project?

**Comment by gsotiris** [comment]
Thank you for quick response, 

Yes it was installed successfully and i could see it in plugin list and in plugins files in my project.
The problem was that after updating cordova android platform from version 6.4.0 to version 8.0.0 the AndroidManifest.xml was in different folder. 
now it work fine.
