### ISSUE TITLE
save file after scan on iOS

### ISSUE THREAD

**Issue by gsotiris** [foxitsoftware/cordova-plugin-foxitpdf#12]
Hello,

i have installed this plugin on iOS and android, everything works on viewing pdf files and i am trying to scan and save photos to pdf. On android works perfect but on iOS after taking a photo and trying to save the file shows the file system witch is some folders that are created on my app and a folder "NoCloud". In every folder i tried to save the photo, then a pop up appears for successfully file saved, but the file doesn't open at all.  In android it works fine. 
every time i am doing this process on android i can see saved documents i have created but on iOS it doesn't show anything.

the code i am using is similar to the code of documentation, is something else that i am doing wrong or i have to do?

**Comment by CancerQ** [comment]
If you are not using the registered version and the saved file is in the documents folder, you will need to make some changes on the open path
