### ISSUE TITLE
cordova foxitpdf can't upload to Testflight(Appstore)

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#16]
Hi All,
I encountered the following issue:
"cordova-plugin-foxitpdf": "^8.3.0"
When validate app and upload to Testflight
<img width="752" alt="Screenshot at Nov 28 14-27-33" src="https://user-images.githubusercontent.com/118706956/204220898-12a5816f-ab7d-4e2d-a238-915d8033ed04.png">
**Version xcode: 14.0.1**
<img width="534" alt="Screenshot at Nov 28 14-38-13" src="https://user-images.githubusercontent.com/118706956/204220923-43c5b68c-c2a5-401b-9ef0-35eff0a2eed4.png">
please support me!
Thank you all!

**Comment by Kroberus** [comment]
@xinqiangSong

**Comment by CancerQ** [comment]
> @xinqiangSong 请支持我！

![image](https://user-images.githubusercontent.com/18671767/204225139-5f6c8a28-cc41-4c73-9322-d8efb0a2d5a2.png)
![image](https://user-images.githubusercontent.com/18671767/204225266-876c2f9c-e9c9-4141-b885-aed6f560062b.png)
Review the instructions, run the script, and use the trimmed real device library

**Comment by Kroberus** [comment]
@CancerQ 
I have tried the following:
<img width="656" alt="Screenshot at Nov 28 16-59-37" src="https://user-images.githubusercontent.com/118706956/204249834-eb4e8f21-a707-4f83-b4fa-38308c7dd07f.png">
**result:**
<img width="309" alt="Screenshot at Nov 28 17-01-13" src="https://user-images.githubusercontent.com/118706956/204249874-1f38c4ba-4c91-4d5b-b22e-122be121f8c0.png">
Please show me step by step
How to create run script in xcode
Thank you!
