### ISSUE TITLE
Save to a new file!

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#17]
Hi all,
**When using the new save file function, how do I get the path of the saved file?**
Thank!
![rn_image_picker_lib_temp_a86150f0-2895-4651-8ba9-953f30d5ae54](https://user-images.githubusercontent.com/118706956/204705157-b20f3f88-95d0-4ad8-830c-da173cc5dc68.jpg)

**Comment by xinqiangSong** [comment]
There is currently no method to obtain the saved path, but users can customize the saved path， as follows：
`    mUiExtensionsManager.setSavePath(your save path);`

**Comment by xinqiangSong** [comment]
> Hi all, **When using the new save file function, how do I get the path of the saved file?** Thank! ![rn_image_picker_lib_temp_a86150f0-2895-4651-8ba9-953f30d5ae54](https://user-images.githubusercontent.com/118706956/204705157-b20f3f88-95d0-4ad8-830c-da173cc5dc68.jpg)

There is currently no method to obtain the saved path, but users can customize the saved path， as follows：
mUiExtensionsManager.setSavePath(your save path);

**Comment by xinqiangSong** [comment]
hi, @Kroberus 
There is currently no method to obtain the saved path, but users can customize the saved path， as follows：
mUiExtensionsManager.setSavePath(your save path);

**Comment by xinqiangSong** [comment]
Hi, @Kroberus 
Currently, there is no method to obtain the saved path.
