### ISSUE TITLE
Customizable according to user needs

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#18]
Hi all,
**Is there a way to hide features that don't need to be used by code!**
Thank!
![IMG_1363](https://user-images.githubusercontent.com/118706956/205585684-15717ffa-8305-4fc8-887e-a5bc6196faef.PNG)

**Comment by Kroberus** [comment]
@xinqiangSong 
please support me!

**Comment by xinqiangSong** [comment]
> Hi all, **Is there a way to hide features that don't need to be used by code!** Thank! ![IMG_1363](https://user-images.githubusercontent.com/118706956/205585684-15717ffa-8305-4fc8-887e-a5bc6196faef.PNG)

--------------
Hi, @Kroberus 
Currently, the plug-in does not provide relevant methods to remove these tools,  
but you can add the following code to the
 [cordova-plugin-foxitpdf # com.foxit.cordova.plugin.ReaderActivity #onCreate ]
 file to meet your needs:

` @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        AppTheme.setThemeFullScreen(this);
        ActManager.getInstance().setCurrentActivity(this);
        AppStorageManager.setOpenTreeRequestCode(REQUEST_OPEN_DOCUMENT_TREE);

        Config config = null;
        try {
            String configPath = "www/plugins/cordova-plugin-foxitpdf/uiextensions_config.json";
            InputStream stream = getApplicationContext().getResources().getAssets().open(configPath);
            config = new Config(stream);
            config.modules.enableAnnotations(FoxitPdf.mEnableAnnotations);
        } catch (IOException e) {
            e.printStackTrace();
        }
        pdfViewCtrl = new PDFViewCtrl(getApplicationContext());
        uiextensionsManager = new UIExtensionsManager(this, pdfViewCtrl, config);
        uiextensionsManager.setAttachedActivity(this);
        pdfViewCtrl.setUIExtensionsManager(uiextensionsManager);
        pdfViewCtrl.setAttachedActivity(this);
        pdfViewCtrl.registerDocEventListener(docListener);
        uiextensionsManager.onCreate(this, pdfViewCtrl, null);
        for (Map.Entry<Integer, Boolean> entry : FoxitPdf.mBottomBarItemStatus.entrySet()) {
            int index = entry.getKey();
            int visible = entry.getValue() ? View.VISIBLE : View.GONE;
            uiextensionsManager.getBarManager().setItemVisibility(IBarsHandler.BarName.BOTTOM_BAR, BaseBar.TB_Position.Position_CENTER, index, visible);
        }

        for (Map.Entry<Integer, Boolean> entry : FoxitPdf.mTopBarItemStatus.entrySet()) {
            int index = entry.getKey();
            int visible = entry.getValue() ? View.VISIBLE : View.GONE;
            if (index == 0) {
                uiextensionsManager.getBarManager().setItemVisibility(IBarsHandler.BarName.TOP_BAR, BaseBar.TB_Position.Position_LT, index, visible);
            } else {
                uiextensionsManager.getBarManager().setItemVisibility(IBarsHandler.BarName.TOP_BAR, BaseBar.TB_Position.Position_RB, index - 1, visible);
            }
        }

        **_Task task = new Task(null) {
            @Override
            protected void execute() {
                List<MainCenterItemBean> toolItems = uiextensionsManager.getMainFrame().getCenterItems();
                for (MainCenterItemBean itemBean : toolItems) {
                    if (itemBean.type == ToolbarItemConfig.ITEM_HOME_TAB) {
                        List<ToolItemBean> tools = itemBean.toolItems;
                        for (int i = tools.size() - 1; i >= 0; i--) {
                            ToolItemBean toolItemBean = tools.get(i);
                            if (toolItemBean.type != 7) { // 7 -- Add item id, keep add item
                                tools.remove(toolItemBean);
                            }
                        }
                        itemBean.toolItems = tools;
                        break;
                    }
                }
                AppThreadManager.getInstance().runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        uiextensionsManager.getMainFrame().setCenterItems(toolItems);
                    }
                });
            }
        };
        pdfViewCtrl.addTask(task);_**
        
        String filePathSaveTo = getIntent().getExtras().getString("filePathSaveTo");
        if (!TextUtils.isEmpty(filePathSaveTo)) {
            uiextensionsManager.setSavePath(filePathSaveTo);
        }

        if (Build.VERSION.SDK_INT >= 30 && !AppFileUtil.isExternalStorageLegacy()) {
            AppStorageManager storageManager = AppStorageManager.getInstance(this);
            boolean needPermission = storageManager.needManageExternalStoragePermission();
            if (!AppStorageManager.isExternalStorageManager() && needPermission) {
                storageManager.requestExternalStorageManager(this, REQUEST_EXTERNAL_STORAGE_MANAGER);
            } else if (!needPermission) {
                checkStorageState();
            } else {
                openDocument();
            }
        } else if (Build.VERSION.SDK_INT >= 23) {
            checkStorageState();
        } else {
            openDocument();
        }

        setContentView(uiextensionsManager.getContentView());
    }`

**Comment by xinqiangSong** [comment]
@Kroberus 
![image](https://user-images.githubusercontent.com/8839082/206078595-70dbe7ae-e32a-46ec-9726-effa457b81ac.png)

**Comment by Kroberus** [comment]
@xinqiangSong thanks for the answer!
Please show me how to fix it on ios. Thank you!

**Comment by CancerQ** [comment]
> @xinqiangSong感谢你的回答！ 请告诉我如何在 ios 上修复它。谢谢你！
Please modify the method - [FoxitPdf FoxitPdfPreview:] in the file foxitpdf#com.foxit.cordova.plugin.FoxitPdf.m.
`# pragma mark -- Foxit preview
-(void)FoxitPdfPreview:(NSString *)filePath {
    
    self.pdfViewControl = [[FSPDFViewCtrl alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    [self.pdfViewControl setRMSAppClientId:@"972b6681-fa03-4b6b-817b-c8c10d38bd20" redirectURI:@"com.foxitsoftware.com.mobilepdf-for-ios://authorize"];
    [self.pdfViewControl registerDocEventListener:self];
    
    NSString *configPath = [[NSBundle mainBundle] pathForResource:@"uiextensions_config" ofType:@"json"];
    UIExtensionsConfig* uiConfig = [[UIExtensionsConfig alloc] initWithJSONData:[NSData dataWithContentsOfFile:configPath]];
    if(self.isEnableAnnotations == NO) {
        uiConfig.loadAttachment = NO;
        uiConfig.tools = [[NSMutableSet<NSString *> alloc] initWithObjects:Tool_Select,Tool_Signature, nil];
    }
    self.extensionsMgr = [[UIExtensionsManager alloc] initWithPDFViewControl:self.pdfViewControl configurationObject:uiConfig];
    self.pdfViewControl.extensionsManager = self.extensionsMgr;
    self.extensionsMgr.delegate = self;
    
    for (FSMainTopbarToolTagItem *tagItem in self.extensionsMgr.topToolbar.tagItems) {
        if (tagItem.toolTag == FSMainTopbarToolTagHome) {
            tagItem.readToolbarItems = @[];
            break;
        }
    }
    
    //load doc
    if (filePath == nil) {
        filePath = [[NSBundle mainBundle] pathForResource:@"getting_started_ios" ofType:@"pdf"];
    }
    
    self.pdfViewController = [[PDFViewController alloc] init];
    self.pdfViewController.extensionsManager = self.extensionsMgr;
    self.pdfViewController.view = self.pdfViewControl;
    
    self.pdfRootViewController = [[UINavigationController alloc] initWithRootViewController:self.pdfViewController];
    self.pdfRootViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    self.pdfRootViewController.navigationBarHidden = YES;
    for (int i = 0; i < self.toolbarItemStatus.count; i++) {
        NSMutableDictionary* status = self.toolbarItemStatus[i];
        FS_TOOLBAR_ITEM_TAG itemTag = [status[@"itemTag"] intValue];
        id obj = [status objectForKey:@"hidden"];
        BOOL isHidden = obj ? [obj boolValue] : NO;
        [self.extensionsMgr setToolbarItemHiddenWithTag:itemTag hidden:isHidden];
    }
    for (int i = 0; i < self.bottomBarItemStatus.count; i++) {
        NSMutableDictionary* status = self.bottomBarItemStatus[i];
        FS_TOOLBAR_ITEM_TAG itemTag = [status[@"itemTag"] intValue];
        id obj = [status objectForKey:@"hidden"];
        BOOL isHidden = obj ? [obj boolValue] : NO;
        [self.extensionsMgr setToolbarItemHiddenWithTag:itemTag hidden:isHidden];
    }
    
    for (int i = 0; i < self.topBarItemStatus.count; i++) {
        NSMutableDictionary* status = self.topBarItemStatus[i];
        FS_TOOLBAR_ITEM_TAG itemTag = [status[@"itemTag"] intValue];
        id obj = [status objectForKey:@"hidden"];
        BOOL isHidden = obj ? [obj boolValue] : NO;
        [self.extensionsMgr setToolbarItemHiddenWithTag:itemTag hidden:isHidden];
    }

    
    if(self.filePathSaveTo && self.filePathSaveTo.length >0){
        self.extensionsMgr.preventOverrideFilePath = self.filePathSaveTo;
    }
    
    __block CDVPluginResult *pluginResult = nil;
    
    void (^block)(void) = ^{
        [pluginResult setKeepCallback:[NSNumber numberWithBool:YES]];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:self.pluginCommand.callbackId];
    };
    
    __weak FoxitPdf* weakSelf = self;
    [self.pdfViewControl openDoc:filePath
                        password:self.filePassword
                      completion:^(FSErrorCode error) {
                          if (error != FSErrSuccess) {
                              
                              pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR
                                                           messageAsDictionary:@{@"FSErrorCode":@(FSErrSuccess), @"info":@"failed open the pdf"}];
                              block();
                              
                              dispatch_time_t delayTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC));
                              
                              dispatch_after(delayTime, dispatch_get_main_queue(), ^{
                                  [weakSelf showAlertViewWithTitle:@"error" message:@"Failed to open the document"];
                                  [weakSelf.viewController dismissViewControllerAnimated:YES completion:nil];
                              });
                              
                              [[NSNotificationCenter defaultCenter] removeObserver:weakSelf];
                          }else{
                              self.currentDoc = self.pdfViewControl.currentDoc;
                              pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK
                                                           messageAsDictionary:@{@"FSErrorCode":@(FSErrSuccess), @"info":@"Open the document successfully"}];
                              block();
                              // Run later to avoid the "took a long time" log message.
                              weakSelf.pdfRootViewController.modalPresentationStyle = UIModalPresentationFullScreen;
                              dispatch_async(dispatch_get_main_queue(), ^{
                                  [weakSelf.viewController presentViewController:weakSelf.pdfRootViewController animated:YES completion:nil];
                              });
                          }
                      }];
    //    self.pdfViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    
    self.topToolbarVerticalConstraints = @[];
    
    self.extensionsMgr.goBack = ^() {
        [weakSelf.viewController dismissViewControllerAnimated:YES completion:nil];
        [[NSNotificationCenter defaultCenter] removeObserver:weakSelf];
    };
    
    [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(handleStatusBarOrientationChange:)
                                                name:UIApplicationDidChangeStatusBarOrientationNotification object:nil];
    
}`

**Comment by Kroberus** [comment]
@CancerQ 
Thank you for supporting me!
When I tried the above code it worked.
![IMG_0028](https://user-images.githubusercontent.com/118706956/229427666-8ce90e23-1c45-440e-8837-551cc60defd2.PNG)
1. Please give me the code list item in the tool list section. So that I can add optionally to the array FSMainTopBarToolTagHome. So that when I initialize foxitPDF I already have the tools that I often use

![IMG_0030](https://user-images.githubusercontent.com/118706956/229428415-0eddfebd-335d-44f2-b93c-ed1b5cfece14.PNG)
![Screenshot 2023-04-03 at 1 12 17 PM](https://user-images.githubusercontent.com/118706956/229428444-2a745c82-d31e-40ad-8513-0717f4560c4a.png)
![IMG_0029](https://user-images.githubusercontent.com/118706956/229428471-d76a3a8c-de3e-4f36-bb04-98c000a7a155.PNG)

2. How can I hide the features that I don't use in the tool list?

![IMG_0030](https://user-images.githubusercontent.com/118706956/229428956-59bb56cd-eba7-4301-8d14-3396d97e9e84.PNG)

**Comment by Kroberus** [comment]
@CancerQ Thank you for supporting me!

**Comment by CancerQ** [comment]
![image](https://user-images.githubusercontent.com/18671767/230290819-76b9f089-ae37-4d14-8d66-6bd74ac156d7.png)
You can configure json files in the ios/ Android directory to disable or enable some features

**Comment by CancerQ** [comment]
> ![image](https://user-images.githubusercontent.com/18671767/230290819-76b9f089-ae37-4d14-8d66-6bd74ac156d7.png) You can configure json files in the ios/ Android directory to disable or enable some features

@Kroberus

**Comment by CancerQ** [comment]
> @CancerQ 谢谢你支持我！ 当我尝试上面的代码时，它起作用了。 ![IMG_0028](https://user-images.githubusercontent.com/118706956/229427666-8ce90e23-1c45-440e-8837-551cc60defd2.PNG)
> 
> 1. 请给我工具列表部分中的代码列表项。这样我就可以选择性地向数组 FSMainTopBarToolTagHome 添加。这样当我初始化 foxitPDF 时，我已经拥有了我经常使用的工具
> 
> ![IMG_0030](https://user-images.githubusercontent.com/118706956/229428415-0eddfebd-335d-44f2-b93c-ed1b5cfece14.PNG) ![截图 2023-04-03 1 12 17 PM](https://user-images.githubusercontent.com/118706956/229428444-2a745c82-d31e-40ad-8513-0717f4560c4a.png) ![IMG_0029](https://user-images.githubusercontent.com/118706956/229428471-d76a3a8c-de3e-4f36-bb04-98c000a7a155.PNG)
> 
> 2. 如何在工具列表中隐藏我不使用的功能？
> 
> ![IMG_0030](https://user-images.githubusercontent.com/118706956/229428956-59bb56cd-eba7-4301-8d14-3396d97e9e84.PNG)

1.
![image](https://user-images.githubusercontent.com/18671767/230292133-1e46726d-2f95-4a70-9200-63725d1f9e5f.png)
![image](https://user-images.githubusercontent.com/18671767/230292988-43ba89c1-f88f-4c2a-9814-133c957e08e0.png)
![image](https://user-images.githubusercontent.com/18671767/230293130-d8c12710-1c20-4d15-b020-10de36c6aae6.png)
You can according to uiextensionsDynamic.framework/Headers/FSReadToolbarItem.h, use - [FSReadToolbarItem initWithToolSettingType:] constructor, Using linkFSReadToolSettingsTypeXXX initializes the corresponding type
2.
![image](https://user-images.githubusercontent.com/18671767/230293331-2c96fc3f-e9c7-4909-b6a6-13a3b074b427.png)
You can configure json files in the ios/ Android directory to disable or enable some features

**Comment by Kroberus** [comment]
@CancerQ 
Thank you for support me!
When I tried the above code it worked.
I want to create home tab as follows but i try and still not successful
How can I make a home tab. Please show me code example thanks.
I don't know much about objective C.
![Screenshot 2023-04-17 at 11 51 06 AM](https://user-images.githubusercontent.com/118706956/232382534-ca9d24a0-b220-48f9-b466-ce90d328f72b.png)
![Screenshot 2023-04-17 at 11 31 47 AM](https://user-images.githubusercontent.com/118706956/232382603-19b0a8c6-2635-4a3d-bf7f-a537b406995c.png)

**Comment by CancerQ** [comment]
> @CancerQ 谢谢你支持我！ 当我尝试上面的代码时，它起作用了。 我想按如下方式创建主页选项卡，但我尝试了但仍然没有成功 如何制作主页选项卡。请给我看代码示例谢谢。 我对目标C了解不多。 ![截图 2023-04-17 11 51 06 AM](https://user-images.githubusercontent.com/118706956/232382534-ca9d24a0-b220-48f9-b466-ce90d328f72b.png) ![屏幕截图 2023-04-17 上午 11 点 31 点 47 分](https://user-images.githubusercontent.com/118706956/232382603-19b0a8c6-2635-4a3d-bf7f-a537b406995c.png)

A tagitem is not a mutable array, so you have to copy the tagitem into a mutable array, add whatever you want, and then assign the mutable array to the immutable tagitem

**Comment by CancerQ** [comment]
@Kroberus 
`NSMutableArray *tmp = self.extensionMgr.topToolbar.tagItems ? self.extensionMgr.topToolbar.tagItems.[].mutablcopy: @[].mutablcopy;
[tmp addObject:#<your item>];
self.extensionMgr.topToolbar.tagItems = tmp;`

**Comment by CancerQ** [comment]
No update for a long time, close the issue
