### ISSUE TITLE
Bluetooth in foxitpdf

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#19]
Hi all,
When uploading the app to testflight I get the message that:
Foxit PDF is using bluetooth( "NSBluetoothAlwaysUsageDescription, NSBluetoothPeripheralUsageDescription").
-> Please tell me which function is using bluetooth.
-> If you don't use those functions, can you turn off the request to use bluetooth?
Thank all!
![23](https://user-images.githubusercontent.com/118706956/205619215-98338a84-f6cc-419b-8371-f7df29022ad2.PNG)

**Comment by Kroberus** [comment]
@xinqiangSong 
please support me!

**Comment by CancerQ** [comment]
> @xinqiangSong 请支持我！

The reason why Bluetooth is needed is that the pencil drawing will know whether to connect the Apple Pencil to achieve a better experience. Whether the interface needs to apply for Bluetooth permission will be provided in a subsequent version. But in any case, you need to add the bluetooth permission description in the info.plist file
