### ISSUE TITLE
Plugin Error: 'Filed to Open this File' Show Toast Message.

### ISSUE THREAD

**Issue by MRUNetwork** [foxitsoftware/cordova-plugin-foxitpdf#2]
Plugin Error: 'Filed to Open this File' Show Toast Message.

show Error messages: "Success to initialize Foxit library."

`
                    FoxitPdf.preview(encodeURI(entry.nativeURL), this.onSuccessFun, this.onErrorFun);
                    `

how to solve this problem? thanks.

**Comment by niuemperor** [comment]
Would you show me the error log ? @GameAppsBD

**Comment by nebulr** [comment]
Yea I also am getting this error. There really aren't any error messages to show. In fact the library just keeps saying it was a success `Success :  Succeed to initialize Foxit library.`

**Comment by nebulr** [comment]
I noticed that there were some code updates to what is currently hosted in npm. I updated to that codebase.. Unfortunately I am still getting the "Failed to open this file" now without any errors whatsoever

**Comment by cabaird** [comment]
I am seeing the same issue.

**Comment by cabaird** [comment]
From what I can see, there is no `FoxitRDK.jar` in this project.  I assume there is a step to add this file where it is needed, separately from the plugin add process?  Is that what is causing our issues?  This file being either absent or in the wrong place?

**Comment by nebulr** [comment]
From what I have been told from the technical sales person is this is a permissions issues with SDK versions greater than API 22. This is the code they gave me that is supposed to work for API 23 android 6.0 but I still can't get it working. Might work for you though : 

`package com.foxit.cordova.plugin;

import android.Manifest;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.util.Log;
import android.view.Menu;
import android.widget.RelativeLayout;
import android.support.v4.app.FragmentActivity;

import com.foxit.sdk.PDFViewCtrl;
import com.foxit.uiextensions.UIExtensionsManager;
import com.foxit.uiextensions.pdfreader.impl.PDFReader;

import org.apache.cordova.CordovaActivity;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.Charset;


public class ReaderActivity extends FragmentActivity {
    private static final int REQUEST_CODE = 1;
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE)!= PackageManager.PERMISSION_GRANTED) {
            Log.i("perm","failed");
            // If has no permission, then request the permission.
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},REQUEST_CODE);}

        else {
            Log.i("perm","success");
            viewdoc();
        }


        /*
        RelativeLayout relativeLayout = new RelativeLayout(this);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);



        PDFViewCtrl pdfViewCtrl = new PDFViewCtrl(this);

        relativeLayout.addView(pdfViewCtrl, params);
        relativeLayout.setWillNotDraw(false);
        relativeLayout.setBackgroundColor(Color.argb(0xff, 0xe1, 0xe1, 0xe1));
        relativeLayout.setDrawingCacheEnabled(true);
        setContentView(relativeLayout);

        String UIExtensionsConfig = "{\n" +
                "    \"defaultReader\": true,\n" +
                "    \"modules\": {\n" +
                "        \"readingbookmark\": true,\n" +
                "        \"outline\": true,\n" +
                "        \"annotations\": true,\n" +
                "        \"thumbnail\" : true,\n" +
                "        \"attachment\": true,\n" +
                "        \"signature\": true,\n" +
                "        \"search\": true,\n" +
                "        \"pageNavigation\": true,\n" +
                "        \"form\": true,\n" +
                "        \"selection\": true,\n" +
                "        \"encryption\" : true\n" +
                "    }\n" +
                "}\n";

        InputStream stream = new ByteArrayInputStream(UIExtensionsConfig.getBytes(Charset.forName("UTF-8")));
        UIExtensionsManager.Config config = new UIExtensionsManager.Config(stream);

        UIExtensionsManager uiextensionsManager = new UIExtensionsManager(this, relativeLayout, pdfViewCtrl, config);
        uiextensionsManager.setAttachedActivity(this);
        pdfViewCtrl.setUIExtensionsManager(uiextensionsManager);
        PDFReader mPDFReader = (PDFReader) uiextensionsManager.getPDFReader();
        mPDFReader.onCreate(this, pdfViewCtrl, null);
        mPDFReader.openDocument(getIntent().getExtras().getString("path"), null);
        setContentView(mPDFReader.getContentView());
        mPDFReader.onStart(this);
        */
    }

    public void viewdoc(){

        RelativeLayout relativeLayout = new RelativeLayout(this);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);



        PDFViewCtrl pdfViewCtrl = new PDFViewCtrl(this);

        relativeLayout.addView(pdfViewCtrl, params);
        relativeLayout.setWillNotDraw(false);
        relativeLayout.setBackgroundColor(Color.argb(0xff, 0xe1, 0xe1, 0xe1));
        relativeLayout.setDrawingCacheEnabled(true);
        setContentView(relativeLayout);

        String UIExtensionsConfig = "{\n" +
                "    \"defaultReader\": true,\n" +
                "    \"modules\": {\n" +
                "        \"readingbookmark\": true,\n" +
                "        \"outline\": true,\n" +
                "        \"annotations\": true,\n" +
                "        \"thumbnail\" : true,\n" +
                "        \"attachment\": true,\n" +
                "        \"signature\": true,\n" +
                "        \"search\": true,\n" +
                "        \"pageNavigation\": true,\n" +
                "        \"form\": true,\n" +
                "        \"selection\": true,\n" +
                "        \"encryption\" : true\n" +
                "    }\n" +
                "}\n";

        InputStream stream = new ByteArrayInputStream(UIExtensionsConfig.getBytes(Charset.forName("UTF-8")));
        UIExtensionsManager.Config config = new UIExtensionsManager.Config(stream);

        UIExtensionsManager uiextensionsManager = new UIExtensionsManager(this, relativeLayout, pdfViewCtrl, config);
        uiextensionsManager.setAttachedActivity(this);

        pdfViewCtrl.setUIExtensionsManager(uiextensionsManager);




// Define a request code. private static final int REQUEST_CODE = 1;


        PDFReader mPDFReader = (PDFReader) uiextensionsManager.getPDFReader();
        mPDFReader.onCreate(this, pdfViewCtrl, null);
        mPDFReader.openDocument(getIntent().getExtras().getString("path"), null);
        setContentView(mPDFReader.getContentView());
        mPDFReader.onStart(this);

    }


    @Override public void onRequestPermissionsResult(int requestCode,String permissions[], int[] grantResults) {
        Log.i("perm","requesting");
        switch (requestCode) {
            case REQUEST_CODE: {
        // 1.If the request is cancelled, the result array is empty.
         // 2.The permission was granted.

            if (grantResults.length > 0  && grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                Log.i("perm","granted");
                viewdoc();

                } else {
                    // permission was denied. Disable the functionality that depends on this permission.
                }

    }
            return;
        }

    }

}`

**Comment by nebulr** [comment]
I finally was able to get this figured out. Turns out the foxit library will **not** accept file paths in the following format : file://some/file/path
You should run some code like this before using the file path in the foxit plugin : 
```
...
            console.log (doc);
            let url = decodeURIComponent(doc.url.replace('file://', ''));
            console.log (doc, url);
            window.FoxitPdf.preview(url,
...
```

**Comment by cabaird** [comment]
Great catch @nebulr 
This was a tough one for me as well.  One way to fix this on the plugin side could be to simply change `line 79` of `ReaderActivity.java` to add a string replace

```
    mPDFReader.openDocument(getIntent().getExtras().getString("path").replace("file://", ""), null);
```

This would allow us to use the normal method of generating file paths in javascript using 'cordova-plugin-file'
