### ISSUE TITLE
I have some issue

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#20]
@xinqiangSong 
I use cordova plugin foxit but I am facing the following problem:
- When I add functions to the home tab and use everything is normal but when I go back in the functions in the home tab are gone without saving. How can I save the added functionality for future sessions.
Please support me! Thank you!
![2](https://user-images.githubusercontent.com/118706956/224283818-919675b5-d781-464c-a83f-ca831754f93b.PNG)
![1](https://user-images.githubusercontent.com/118706956/224283793-79ed1245-4e96-4cc9-bab6-ef4e7b40520f.PNG)

**Comment by Kroberus** [comment]
@xinqiangSong @niusumilux Please support me! Thank you!

**Comment by Kroberus** [comment]
@xinqiangSong 
When I add functions to the home tab and use it everything is fine but when I open a new file with foxitpdf the functions in the home tab disappear without saving. How can I save added functionality for future sessions.
I have issue as above. Please support me! Thank you!

**Comment by javacsharp** [comment]
@CancerQ 
Does that mean even if we customize the top menu it will only work for the current session.
Next time we open a document the settings revert back to default?
Is there any way to save the settings either by feature or by programmatically?

**Comment by CancerQ** [comment]
> @CancerQ 这是否意味着即使我们自定义顶部菜单它也只适用于当前会话？ 下次我们打开文档时，设置会恢复为默认设置吗？ 有没有办法通过功能或编程方式保存设置？

Like I said before, you just need to make sure that UIExtensionsManager is not released

**Comment by javacsharp** [comment]
@CancerQ 
Thanks for your answer.

> Like I said before, you just need to make sure that UIExtensionsManager is not released

So does that mean we must edit the code to keep UIExtensionsManager not to be released everytime we close the document?
And do we need to do that in Android and iOS separately?
Can you show me how to do that? 
Our technical team have experiences in Javascript in general but not in native Android and iOS development.
We intend to buy the software but it's quite frustrated that everytime we close the document the settings is reverted to default settings.

**Comment by CancerQ** [comment]
> @CancerQ Thanks for your answer.
> 
> > Like I said before, you just need to make sure that UIExtensionsManager is not released
> 
> So does that mean we must edit the code to keep UIExtensionsManager not to be released everytime we close the document? And do we need to do that in Android and iOS separately? Can you show me how to do that? Our technical team have experiences in Javascript in general but not in native Android and iOS development. We intend to buy the software but it's quite frustrated that everytime we close the document the settings is reverted to default settings.
[Take a look at this](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/tree/feature/%2320)

**Comment by Kroberus** [comment]
> > @CancerQ Thanks for your answer.
> > > Like I said before, you just need to make sure that UIExtensionsManager is not released
> > 
> > 
> > So does that mean we must edit the code to keep UIExtensionsManager not to be released everytime we close the document? And do we need to do that in Android and iOS separately? Can you show me how to do that? Our technical team have experiences in Javascript in general but not in native Android and iOS development. We intend to buy the software but it's quite frustrated that everytime we close the document the settings is reverted to default settings.
> > [Take a look at this](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/tree/feature/%2320)

I try and it working. thank you very much.
Can you fix it on android. Please support me!

**Comment by xinqiangSong** [comment]
> > > @CancerQ Thanks for your answer.
> > > > Like I said before, you just need to make sure that UIExtensionsManager is not released
> > > 
> > > 
> > > So does that mean we must edit the code to keep UIExtensionsManager not to be released everytime we close the document? And do we need to do that in Android and iOS separately? Can you show me how to do that? Our technical team have experiences in Javascript in general but not in native Android and iOS development. We intend to buy the software but it's quite frustrated that everytime we close the document the settings is reverted to default settings.
> > > [Take a look at this](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/tree/feature/%2320)
> 
> I try and it working. thank you very much. Can you fix it on android. Please support me!

@Kroberus @javacsharp 
I have submitted the Android code in the feature#20 branch, please try again.
[Take a look at this](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/blob/feature/%2320/src/android/com/foxit/cordova/plugin/ReaderActivity.java)

**Comment by CancerQ** [comment]
No update for a long time, close the issue
