### ISSUE TITLE
How to add custom tab

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#21]
@xinqiangSong 
How to add custom tabs and add favorite functions to it. And when I open the app, it's always there.
Please support me! Thank you!
![IMG_2164](https://user-images.githubusercontent.com/118706956/224285600-dd59083f-9327-44df-af14-41fae7191e71.PNG)

**Comment by Kroberus** [comment]
@xinqiangSong @niusumilux Please support me! Thank you!

**Comment by xinqiangSong** [comment]
> @xinqiangSong @niusumilux Please support me! Thank you!
Sorry, we currently do not support inserting tabs, but if you need it , you can contact us, after our evaluation, it may be supported in the next version.
https://www.foxitsoftware.cn/company/contact.html

**Comment by javacsharp** [comment]
@xinqiangSong 
I am sorry but I want to clarify this before our company decides to buy the software.
Currently this plugin doesn't support user to customize the top toolbar but is there a way to do it programmatically?
Is there a way to edit source code to change the list of tabs and content of each tab?

**Comment by CancerQ** [comment]
> @xinqiangSong I am sorry but I want to clarify this before our company decides to buy the software. Currently this plugin doesn't support user to customize the top toolbar but is there a way to do it programmatically? Is there a way to edit source code to change the list of tabs and content of each tab?

Sorry, we currently do not support inserting tabs, but if you need it , you can contact us, after our evaluation, it may be supported in the next version.
https://www.foxitsoftware.cn/company/contact.html

**Comment by xinqiangSong** [comment]
> @xinqiangSong I am sorry but I want to clarify this before our company decides to buy the software. Currently this plugin doesn't support user to customize the top toolbar but is there a way to do it programmatically? Is there a way to edit source code to change the list of tabs and content of each tab?

Yes, it is not supported in the current version. Currently, this function cannot be implemented by changing the source code of the plug-in. You need to modify the source code of ‘FoxitRDKUIExtensions.aar’. If you need it, we need to evaluate it, and later versions will add this function.
