### ISSUE TITLE
Branch feature/#20 have a some issue

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#22]
@CancerQ 
I opened the pdf file and closed the pdf file many times the application encountered the following problem. Please support me. Do you plan to merge this branch into master branch? Thanks you!
![1C4F1670-CA8F-43B0-BFFF-45F383591342](https://user-images.githubusercontent.com/118706956/232432325-5414e2e6-4893-4acb-9475-3b5c9df753e9.png)
![Screenshot 2023-04-17 at 3 13 39 PM](https://user-images.githubusercontent.com/118706956/232432340-7678323c-1c50-44b8-93dd-0ac3e88accbc.png)

**Comment by CancerQ** [comment]
You need to completely close the view of the document before you can open it again, because your code doesn't do a good job of controlling it.
We're not planning to merge into the master branch, it's not something we're thinking about right now, you'll have to adjust it yourself
