### ISSUE TITLE
How to use function removeEventListener

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#24]
@xinqiangSong @CancerQ @niusumilux @rowanhanna @niuemperor @yongliang-huang @wjm6677 
I used the same function but it can't remove the added function
It requires GUI code
How can the corresponding gui code be determined when addEventListener 'onDocSaved'
Is there any way to remove or replace function added to addEventListener 'onDocSaved'
![image](https://user-images.githubusercontent.com/118706956/233333305-c1d1421f-6dfd-4a60-a8f7-d8e49d7aed8f.png)

**Comment by Kroberus** [comment]
@xinqiangSong please support me!

**Comment by xinqiangSong** [comment]
> @xinqiangSong please support me!

Sorry, didn't get your point, this method is not responding?

**Comment by Kroberus** [comment]
@xinqiangSong 
how to use method window.FoxitPDF.removeEventListener

**Comment by xinqiangSong** [comment]
@Kroberus 
`    var callback = function(data){
        console.log('mytag: ' +data["type"]);
    };
   
    // add
    window.FoxitPdf.addEventListener('onDocOpened',callback);

   //remove
    window.FoxitPdf.removeEventListener('onDocOpened',callback);`

**Comment by xinqiangSong** [comment]
> @xinqiangSong how to use method window.FoxitPDF.removeEventListener

Please ensure that adding and removing are the same method， like this：
` var callback = function(data){
        console.log('mytag: ' +data["type"]);
    };
    window.FoxitPdf.addEventListener('onDocOpened',callback);

    window.FoxitPdf.removeEventListener('onDocOpened',callback);`
