### ISSUE TITLE
FoxitPDF ios have a issue

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#25]
@CancerQ Please support me! Thanks.

I use mac chip M2.
I use [Foxit PDF SDK for iOS (Objective-C Library)](https://cdn-sdk.foxitsoftware.com/pdf-sdk/download/foxit-mobile-pdf-sdk/ios/8.x/8.4/foxitpdfsdk_8_4_ios.zip)
I have issue when build project
![Screenshot 2023-04-24 at 09 59 04](https://user-images.githubusercontent.com/118706956/233891690-9167ac26-b448-426f-bed1-f3c02c6baaee.png)
![Screenshot 2023-04-24 at 09 59 45](https://user-images.githubusercontent.com/118706956/233891662-353437f5-ad2a-44c5-84e6-4287ed2690c9.png)

Building for iOS Simulator, but linking in dylib built for iOS, file 'xxx/platforms/ios/libs/FoxitPDFScanUI.framework/FoxitPDFScanUI' for architecture arm64

**Comment by CancerQ** [comment]
> @CancerQ请支持我！谢谢。
> 
> 我使用mac芯片M2。 我使用[Foxit PDF SDK for iOS (Objective-C Library)](https://cdn-sdk.foxitsoftware.com/pdf-sdk/download/foxit-mobile-pdf-sdk/ios/8.x/8.4/foxitpdfsdk_8_4_ios.zip) 我在构建项目时遇到问题 ![屏幕截图 2023-04-24 于 09 59 04](https://user-images.githubusercontent.com/118706956/233891690-9167ac26-b448-426f-bed1-f3c02c6baaee.png) ![屏幕截图 2023-04-24 于 09 59 45](https://user-images.githubusercontent.com/118706956/233891662-353437f5-ad2a-44c5-84e6-4287ed2690c9.png)
> 
> 为 iOS 模拟器构建，但在为 iOS 构建的 dylib 中链接，文件 'xxx/platforms/ios/libs/FoxitPDFScanUI.framework/FoxitPDFScanUI' 用于架构 arm64
Please use Any iOS device
![image](https://user-images.githubusercontent.com/18671767/233895701-8e9cb241-77de-4ec3-86fc-276144b5d41c.png)

**Comment by CancerQ** [comment]
> @CancerQ请支持我！谢谢。
> 
> 我使用mac芯片M2。 我使用[Foxit PDF SDK for iOS (Objective-C Library)](https://cdn-sdk.foxitsoftware.com/pdf-sdk/download/foxit-mobile-pdf-sdk/ios/8.x/8.4/foxitpdfsdk_8_4_ios.zip) 我在构建项目时遇到问题 ![屏幕截图 2023-04-24 于 09 59 04](https://user-images.githubusercontent.com/118706956/233891690-9167ac26-b448-426f-bed1-f3c02c6baaee.png) ![屏幕截图 2023-04-24 于 09 59 45](https://user-images.githubusercontent.com/118706956/233891662-353437f5-ad2a-44c5-84e6-4287ed2690c9.png)
> 
> 为 iOS 模拟器构建，但在为 iOS 构建的 dylib 中链接，文件 'xxx/platforms/ios/libs/FoxitPDFScanUI.framework/FoxitPDFScanUI' 用于架构 arm64

Please check whether the samples can run normally on m1 equipment, please refer to the configuration of the modification project

**Comment by CancerQ** [comment]
No update for a long time, close the issue
