### ISSUE TITLE
I have a issue

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#26]
@CancerQ Please support me!
when i use the Save and Save as function it returns the same object
How can I tell if I used the save or save as function?
![Screenshot 2023-04-24 at 4 58 33 PM](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)

**Comment by CancerQ** [comment]
> @CancerQ Please support me! when i use the Save and Save as function it returns the same object How can I tell if I used the save or save as function? ![Screenshot 2023-04-24 at 4 58 33 PM](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)

No way to tell at the moment, thank you

**Comment by Kroberus** [comment]
> > @CancerQ Please support me! when i use the Save and Save as function it returns the same object How can I tell if I used the save or save as function? ![Screenshot 2023-04-24 at 4 58 33 PM](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)
> 
> No way to tell at the moment, thank you

Can I use objective C code to tell the difference?

**Comment by CancerQ** [comment]
> > > @CancerQ请支持我！当我使用 Save 和 Save as 函数时，它返回相同的对象 如何判断我使用的是 save 还是 save as 函数？![屏幕截图 2023-04-24 下午 4 时 58 分 33 分](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)
> > 
> > 
> > 暂时不知道，谢谢
> 
> 可以使用目标 C 代码来区分吗？

The source code of the plug-in is indistinguishable, only by modifying the uiextensions source code and recompiling it

**Comment by Kroberus** [comment]
> > > > @CancerQ请支持我！当我使用 Save 和 Save as 函数时，它返回相同的对象 如何判断我使用的是 save 还是 save as 函数？![屏幕截图 2023-04-24 下午 4 时 58 分 33 分](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)
> > > 
> > > 
> > > 暂时不知道，谢谢
> > 
> > 
> > 可以使用目标 C 代码来区分吗？
> 
> The source code of the plug-in is indistinguishable, only by modifying the uiextensions source code and recompiling it

Please show me the compile source code that returns when using save and save as. Thank you!

**Comment by CancerQ** [comment]
> > > > > @CancerQ请支持我！当我使用 Save 和 Save as 函数时，它返回相同的对象 如何判断我使用的是 save 还是 save as 函数？![屏幕截图 2023-04-24 下午 4 时 58 分 33 分](https://user-images.githubusercontent.com/118706956/233965469-db13a554-c9e8-4bcd-b925-235c48a394f1.png)
> > > > 
> > > > 
> > > > 暂时不知道，谢谢
> > > 
> > > 
> > > 可以使用目标 C 代码来区分吗？
> > 
> > 
> > The source code of the plug-in is indistinguishable, only by modifying the uiextensions source code and recompiling it
> 
> Please show me the compile source code that returns when using save and save as. Thank you!

![image](https://user-images.githubusercontent.com/18671767/234163665-c461239e-a88e-4037-96b2-a820140c4d8c.png)
You can check out this part of the code
