### ISSUE TITLE
Ui foxitPDF on ios spilt view ipad

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#27]
@xinqiangSong  @CancerQ Please support me. Thank you!
When using foxit PDF on ipad with split view function have the following problem:
![IMG_1022](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/c4eb0654-a2d9-42eb-9f64-c95f1112e99b)

1. Please show me how to remove the time in the header bar like the picture below
![IMG_1019](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/15ad92bf-c874-4f28-bfcc-38c0ecd4b4cf)

2. How can I always show the header bar without being hidden like the image below?
![IMG_1023](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/b8ea0340-3d03-43e0-9647-3e4aba89e422)

**Comment by Kroberus** [comment]
@xinqiangSong @CancerQ  Please support me. Thank you!

**Comment by CancerQ** [comment]
> @xinqiangSong @CancerQ Please support me. Thank you!
Configure json
![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/18671767/b8db82ac-b7e9-4343-badc-875b738aa36f)

**Comment by Kroberus** [comment]
@CancerQ Thank you!
How to remove the time in the header bar like the picture below
![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/8d0d593a-f45c-4bca-ae87-6ae3da4f9493)

**Comment by Kroberus** [comment]
> @CancerQ Thank you! How to remove the time in the header bar like the picture below. Please support me! ![image](https://user-images.githubusercontent.com/118706956/244337337-8d0d593a-f45c-4bca-ae87-6ae3da4f9493.png)

**Comment by CancerQ** [comment]
> > @CancerQ Thank you! How to remove the time in the header bar like the picture below. Please support me! ![image](https://user-images.githubusercontent.com/118706956/244337337-8d0d593a-f45c-4bca-ae87-6ae3da4f9493.png)
> > @CancerQ Please support me! Thank you!
remove time label
![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/18671767/6148d14c-009d-496c-8e43-a14c2585ff9d)

**Comment by Kroberus** [comment]
@CancerQ Thank you!
Is there a way to fix it in the FoxitPdf.m file?
In cordova I just use uiextensionsDynamic.framework ,FoxitRDK.framework ,FoxitPDFScanUI.framework.
I tried deleting like the image below before building the project but it didn't work
![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/abec8548-ccf7-4162-8142-7981bbfcac4b)

**Comment by CancerQ** [comment]
> @CancerQ Thank you! Is there a way to fix it in the FoxitPdf.m file? In cordova I just use uiextensionsDynamic.framework ,FoxitRDK.framework ,FoxitPDFScanUI.framework. I tried deleting like the image below before building the project but it didn't work ![image](https://user-images.githubusercontent.com/118706956/245357709-abec8548-ccf7-4162-8142-7981bbfcac4b.png)

You need to recompile uiextensionsDynamic framework, if don't work, please try to clear the cache

**Comment by Kroberus** [comment]
@CancerQ can i use this way to recompile uiextensionsDynamic.framework?

![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/db75ae91-099e-40fc-9464-2b60138594ee)

**Comment by CancerQ** [comment]
> @CancerQ can i use this way to recompile uiextensionsDynamic.framework?
> 
> ![image](https://user-images.githubusercontent.com/118706956/245358713-db75ae91-099e-40fc-9464-2b60138594ee.png)

This isn't compilation, it's just cutting out a multi-architecture library

You need to run this script
![image](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/18671767/e6eeffa6-e42a-4afc-87f7-d069f07abf0d)

**Comment by Kroberus** [comment]
@CancerQ 

> 

@CancerQ it working! Thank you!
