### ISSUE TITLE
I have a issue

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#28]
@CancerQ 
How to hide the Save as function?
Please support me. Thank you!
![IMG_1182](https://github.com/foxitsoftware/cordova-plugin-foxitpdf/assets/118706956/28a1dc35-7e2b-48d9-86d0-4782e24af913)

**Comment by CancerQ** [comment]
> @CancerQ How to hide the Save as function? Please support me. Thank you! ![IMG_1182](https://user-images.githubusercontent.com/118706956/256402452-28a1dc35-7e2b-48d9-86d0-4782e24af913.PNG)

You need to modify the onClickBackButton function of UIExtensionsManager.m and then recompile it. Or implementation - [id < UIExtensionsManagerDelegate > quitUIExtensionsManager: control:] callback

**Comment by CancerQ** [comment]
No update for a long time, close the issue
