### ISSUE TITLE
App Crashes on .preview() call (Android)

### ISSUE THREAD

**Issue by BigJenson** [foxitsoftware/cordova-plugin-foxitpdf#5]
I'm experiencing a complete App-Crash when i try to use this plugin.
After im calling the window.FoxitPdf.preview(filePath,success,error) function the error Callback is called with following message:

> Failed to initialize Foxit library.

Then the App closes completely because its stopping the MainActivity.

**Comment by sq-ricardo-pereira** [comment]
I've been the same problem. Do you have some feedback?

**Comment by BigJenson** [comment]
For me the Fix was to change the License Keys on Android. But with the last Plugin update Android broke again when leaving the Activity (different Exception).

**Comment by niuemperor** [comment]
maybe is the key invalid。please goto our offical website to purchase the license .

http://www.foxitsdk.com/products/mobile-pdf-sdk/request-quote/?from=cordova-plugin-foxitpdf
