### ISSUE TITLE
Unnecessary PDF declared as source-file

### ISSUE THREAD

**Issue by BigJenson** [foxitsoftware/cordova-plugin-foxitpdf#9]
Hi, in the plugin.xml Line 18 the getting_started_ios.pdf is declared as a source-file

`<source-file src="src/ios/getting_started_ios.pdf"/>`

This will copy the tutorial PDF into the actual IOS Project and package it into the App. Is this on purpose? If not, could you remove that line?

**Comment by niuemperor** [comment]
Thank you for your suggestion. 
I will remove it

thank you very much

**Comment by niuemperor** [comment]
hi @BigJenson , i will close it.
